import { createApp } from 'vue';
import App from './App.vue';
import './registerServiceWorker';
import router from './router';
import store from './store';
import Notifications from '@kyvg/vue3-notification';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap';
import './assets/scss/style.scss';
import 'vue-multiselect/dist/vue-multiselect.css';
createApp(App).use(store).use(router).use(Notifications).mount('#app');
